//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfRentingApartementRacheli.ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOApartments", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    public partial class DTOApartments : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ExtraForBedField;
        
        private int FloorField;
        
        private int IdApartmentField;
        
        private WpfRentingApartementRacheli.ServiceReference1.DTOCities IdCitiesField;
        
        private WpfRentingApartementRacheli.ServiceReference1.DTOStreetsNames IdStreetField;
        
        private int MinimumPriceField;
        
        private string NameOwnerField;
        
        private int NumberBedsField;
        
        private string NumberHouseField;
        
        private int NumberRoomsField;
        
        private string PhoneOwnerField;
        
        private bool StatusField;
        
        private string noteField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExtraForBed
        {
            get
            {
                return this.ExtraForBedField;
            }
            set
            {
                this.ExtraForBedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Floor
        {
            get
            {
                return this.FloorField;
            }
            set
            {
                this.FloorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdApartment
        {
            get
            {
                return this.IdApartmentField;
            }
            set
            {
                this.IdApartmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfRentingApartementRacheli.ServiceReference1.DTOCities IdCities
        {
            get
            {
                return this.IdCitiesField;
            }
            set
            {
                this.IdCitiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfRentingApartementRacheli.ServiceReference1.DTOStreetsNames IdStreet
        {
            get
            {
                return this.IdStreetField;
            }
            set
            {
                this.IdStreetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinimumPrice
        {
            get
            {
                return this.MinimumPriceField;
            }
            set
            {
                this.MinimumPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameOwner
        {
            get
            {
                return this.NameOwnerField;
            }
            set
            {
                this.NameOwnerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberBeds
        {
            get
            {
                return this.NumberBedsField;
            }
            set
            {
                this.NumberBedsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumberHouse
        {
            get
            {
                return this.NumberHouseField;
            }
            set
            {
                this.NumberHouseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberRooms
        {
            get
            {
                return this.NumberRoomsField;
            }
            set
            {
                this.NumberRoomsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneOwner
        {
            get
            {
                return this.PhoneOwnerField;
            }
            set
            {
                this.PhoneOwnerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOCities", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    public partial class DTOCities : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdCityField;
        
        private string NameCityField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCity
        {
            get
            {
                return this.IdCityField;
            }
            set
            {
                this.IdCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameCity
        {
            get
            {
                return this.NameCityField;
            }
            set
            {
                this.NameCityField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOStreetsNames", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    public partial class DTOStreetsNames : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdStreetField;
        
        private string StreetNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdStreet
        {
            get
            {
                return this.IdStreetField;
            }
            set
            {
                this.IdStreetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetName
        {
            get
            {
                return this.StreetNameField;
            }
            set
            {
                this.StreetNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOAreas", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    public partial class DTOAreas : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdAreaField;
        
        private string NameAreaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdArea
        {
            get
            {
                return this.IdAreaField;
            }
            set
            {
                this.IdAreaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameArea
        {
            get
            {
                return this.NameAreaField;
            }
            set
            {
                this.NameAreaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOAraesCitiesStreet", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    public partial class DTOAraesCitiesStreet : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private WpfRentingApartementRacheli.ServiceReference1.DTOAreas IdAreaField;
        
        private WpfRentingApartementRacheli.ServiceReference1.DTOCities IdCitiesField;
        
        private WpfRentingApartementRacheli.ServiceReference1.DTOStreetsNames IdStreetDToField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfRentingApartementRacheli.ServiceReference1.DTOAreas IdArea
        {
            get
            {
                return this.IdAreaField;
            }
            set
            {
                this.IdAreaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfRentingApartementRacheli.ServiceReference1.DTOCities IdCities
        {
            get
            {
                return this.IdCitiesField;
            }
            set
            {
                this.IdCitiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfRentingApartementRacheli.ServiceReference1.DTOStreetsNames IdStreetDTo
        {
            get
            {
                return this.IdStreetDToField;
            }
            set
            {
                this.IdStreetDToField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOExtras", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    public partial class DTOExtras : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdExtraField;
        
        private string NameExtraField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdExtra
        {
            get
            {
                return this.IdExtraField;
            }
            set
            {
                this.IdExtraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameExtra
        {
            get
            {
                return this.NameExtraField;
            }
            set
            {
                this.NameExtraField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOExtrasApartements", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    public partial class DTOExtrasApartements : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private WpfRentingApartementRacheli.ServiceReference1.DTOApartments IdAapartmentField;
        
        private WpfRentingApartementRacheli.ServiceReference1.DTOExtras IdExtraField;
        
        private bool StatusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfRentingApartementRacheli.ServiceReference1.DTOApartments IdAapartment
        {
            get
            {
                return this.IdAapartmentField;
            }
            set
            {
                this.IdAapartmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfRentingApartementRacheli.ServiceReference1.DTOExtras IdExtra
        {
            get
            {
                return this.IdExtraField;
            }
            set
            {
                this.IdExtraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOHirers", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    public partial class DTOHirers : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string C_IDHirerField;
        
        private string FhoneNumberHirerField;
        
        private string NameHirerField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C_IDHirer
        {
            get
            {
                return this.C_IDHirerField;
            }
            set
            {
                this.C_IDHirerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FhoneNumberHirer
        {
            get
            {
                return this.FhoneNumberHirerField;
            }
            set
            {
                this.FhoneNumberHirerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameHirer
        {
            get
            {
                return this.NameHirerField;
            }
            set
            {
                this.NameHirerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOImages", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    public partial class DTOImages : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private WpfRentingApartementRacheli.ServiceReference1.DTOApartments IdApartementField;
        
        private byte[] Image1Field;
        
        private int NumImageField;
        
        private bool StatausField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfRentingApartementRacheli.ServiceReference1.DTOApartments IdApartement
        {
            get
            {
                return this.IdApartementField;
            }
            set
            {
                this.IdApartementField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image1
        {
            get
            {
                return this.Image1Field;
            }
            set
            {
                this.Image1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumImage
        {
            get
            {
                return this.NumImageField;
            }
            set
            {
                this.NumImageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Stataus
        {
            get
            {
                return this.StatausField;
            }
            set
            {
                this.StatausField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTORentings", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    public partial class DTORentings : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DateField;
        
        private WpfRentingApartementRacheli.ServiceReference1.DTOHirers IdHirerField;
        
        private int IdRentingField;
        
        private WpfRentingApartementRacheli.ServiceReference1.DTOApartments KodHapartmentField;
        
        private int SumBedsField;
        
        private int SumPaymentField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfRentingApartementRacheli.ServiceReference1.DTOHirers IdHirer
        {
            get
            {
                return this.IdHirerField;
            }
            set
            {
                this.IdHirerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRenting
        {
            get
            {
                return this.IdRentingField;
            }
            set
            {
                this.IdRentingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfRentingApartementRacheli.ServiceReference1.DTOApartments KodHapartment
        {
            get
            {
                return this.KodHapartmentField;
            }
            set
            {
                this.KodHapartmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SumBeds
        {
            get
            {
                return this.SumBedsField;
            }
            set
            {
                this.SumBedsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SumPayment
        {
            get
            {
                return this.SumPaymentField;
            }
            set
            {
                this.SumPaymentField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WpfRentingApartementRacheli.ServiceReference1.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetApartments", ReplyAction="http://tempuri.org/IService1/GetApartmentsResponse")]
        WpfRentingApartementRacheli.ServiceReference1.DTOApartments[] GetApartments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetApartments", ReplyAction="http://tempuri.org/IService1/GetApartmentsResponse")]
        System.Threading.Tasks.Task<WpfRentingApartementRacheli.ServiceReference1.DTOApartments[]> GetApartmentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddApartments", ReplyAction="http://tempuri.org/IService1/AddApartmentsResponse")]
        bool AddApartments(WpfRentingApartementRacheli.ServiceReference1.DTOApartments apartments);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddApartments", ReplyAction="http://tempuri.org/IService1/AddApartmentsResponse")]
        System.Threading.Tasks.Task<bool> AddApartmentsAsync(WpfRentingApartementRacheli.ServiceReference1.DTOApartments apartments);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAreas", ReplyAction="http://tempuri.org/IService1/GetAreasResponse")]
        WpfRentingApartementRacheli.ServiceReference1.DTOAreas[] GetAreas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAreas", ReplyAction="http://tempuri.org/IService1/GetAreasResponse")]
        System.Threading.Tasks.Task<WpfRentingApartementRacheli.ServiceReference1.DTOAreas[]> GetAreasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddArea", ReplyAction="http://tempuri.org/IService1/AddAreaResponse")]
        bool AddArea(WpfRentingApartementRacheli.ServiceReference1.DTOAreas areas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddArea", ReplyAction="http://tempuri.org/IService1/AddAreaResponse")]
        System.Threading.Tasks.Task<bool> AddAreaAsync(WpfRentingApartementRacheli.ServiceReference1.DTOAreas areas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTOAraesCitiesStreets", ReplyAction="http://tempuri.org/IService1/GetTOAraesCitiesStreetsResponse")]
        WpfRentingApartementRacheli.ServiceReference1.DTOAraesCitiesStreet[] GetTOAraesCitiesStreets();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTOAraesCitiesStreets", ReplyAction="http://tempuri.org/IService1/GetTOAraesCitiesStreetsResponse")]
        System.Threading.Tasks.Task<WpfRentingApartementRacheli.ServiceReference1.DTOAraesCitiesStreet[]> GetTOAraesCitiesStreetsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddAraesCitiesStreet", ReplyAction="http://tempuri.org/IService1/AddAraesCitiesStreetResponse")]
        bool AddAraesCitiesStreet(WpfRentingApartementRacheli.ServiceReference1.DTOAraesCitiesStreet araesCitiesStreet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddAraesCitiesStreet", ReplyAction="http://tempuri.org/IService1/AddAraesCitiesStreetResponse")]
        System.Threading.Tasks.Task<bool> AddAraesCitiesStreetAsync(WpfRentingApartementRacheli.ServiceReference1.DTOAraesCitiesStreet araesCitiesStreet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTOCities", ReplyAction="http://tempuri.org/IService1/GetTOCitiesResponse")]
        WpfRentingApartementRacheli.ServiceReference1.DTOCities[] GetTOCities();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTOCities", ReplyAction="http://tempuri.org/IService1/GetTOCitiesResponse")]
        System.Threading.Tasks.Task<WpfRentingApartementRacheli.ServiceReference1.DTOCities[]> GetTOCitiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCities", ReplyAction="http://tempuri.org/IService1/AddCitiesResponse")]
        bool AddCities(WpfRentingApartementRacheli.ServiceReference1.DTOCities cities);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCities", ReplyAction="http://tempuri.org/IService1/AddCitiesResponse")]
        System.Threading.Tasks.Task<bool> AddCitiesAsync(WpfRentingApartementRacheli.ServiceReference1.DTOCities cities);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExtras", ReplyAction="http://tempuri.org/IService1/GetExtrasResponse")]
        WpfRentingApartementRacheli.ServiceReference1.DTOExtras[] GetExtras();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExtras", ReplyAction="http://tempuri.org/IService1/GetExtrasResponse")]
        System.Threading.Tasks.Task<WpfRentingApartementRacheli.ServiceReference1.DTOExtras[]> GetExtrasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddExtras", ReplyAction="http://tempuri.org/IService1/AddExtrasResponse")]
        bool AddExtras(WpfRentingApartementRacheli.ServiceReference1.DTOExtras extras);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddExtras", ReplyAction="http://tempuri.org/IService1/AddExtrasResponse")]
        System.Threading.Tasks.Task<bool> AddExtrasAsync(WpfRentingApartementRacheli.ServiceReference1.DTOExtras extras);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTOExtrasApartements", ReplyAction="http://tempuri.org/IService1/GetTOExtrasApartementsResponse")]
        WpfRentingApartementRacheli.ServiceReference1.DTOExtrasApartements[] GetTOExtrasApartements();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTOExtrasApartements", ReplyAction="http://tempuri.org/IService1/GetTOExtrasApartementsResponse")]
        System.Threading.Tasks.Task<WpfRentingApartementRacheli.ServiceReference1.DTOExtrasApartements[]> GetTOExtrasApartementsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddExtrasApartements", ReplyAction="http://tempuri.org/IService1/AddExtrasApartementsResponse")]
        bool AddExtrasApartements(WpfRentingApartementRacheli.ServiceReference1.DTOExtrasApartements extrasApartements);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddExtrasApartements", ReplyAction="http://tempuri.org/IService1/AddExtrasApartementsResponse")]
        System.Threading.Tasks.Task<bool> AddExtrasApartementsAsync(WpfRentingApartementRacheli.ServiceReference1.DTOExtrasApartements extrasApartements);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTOHirers", ReplyAction="http://tempuri.org/IService1/GetTOHirersResponse")]
        WpfRentingApartementRacheli.ServiceReference1.DTOHirers[] GetTOHirers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTOHirers", ReplyAction="http://tempuri.org/IService1/GetTOHirersResponse")]
        System.Threading.Tasks.Task<WpfRentingApartementRacheli.ServiceReference1.DTOHirers[]> GetTOHirersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddHirers", ReplyAction="http://tempuri.org/IService1/AddHirersResponse")]
        bool AddHirers(WpfRentingApartementRacheli.ServiceReference1.DTOHirers hirers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddHirers", ReplyAction="http://tempuri.org/IService1/AddHirersResponse")]
        System.Threading.Tasks.Task<bool> AddHirersAsync(WpfRentingApartementRacheli.ServiceReference1.DTOHirers hirers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetImages", ReplyAction="http://tempuri.org/IService1/GetImagesResponse")]
        WpfRentingApartementRacheli.ServiceReference1.DTOImages[] GetImages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetImages", ReplyAction="http://tempuri.org/IService1/GetImagesResponse")]
        System.Threading.Tasks.Task<WpfRentingApartementRacheli.ServiceReference1.DTOImages[]> GetImagesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddImages", ReplyAction="http://tempuri.org/IService1/AddImagesResponse")]
        bool AddImages(WpfRentingApartementRacheli.ServiceReference1.DTOImages images);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddImages", ReplyAction="http://tempuri.org/IService1/AddImagesResponse")]
        System.Threading.Tasks.Task<bool> AddImagesAsync(WpfRentingApartementRacheli.ServiceReference1.DTOImages images);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTORentings", ReplyAction="http://tempuri.org/IService1/GetTORentingsResponse")]
        WpfRentingApartementRacheli.ServiceReference1.DTORentings[] GetTORentings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTORentings", ReplyAction="http://tempuri.org/IService1/GetTORentingsResponse")]
        System.Threading.Tasks.Task<WpfRentingApartementRacheli.ServiceReference1.DTORentings[]> GetTORentingsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Addentings", ReplyAction="http://tempuri.org/IService1/AddentingsResponse")]
        bool Addentings(WpfRentingApartementRacheli.ServiceReference1.DTORentings rentings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Addentings", ReplyAction="http://tempuri.org/IService1/AddentingsResponse")]
        System.Threading.Tasks.Task<bool> AddentingsAsync(WpfRentingApartementRacheli.ServiceReference1.DTORentings rentings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStreetsNames", ReplyAction="http://tempuri.org/IService1/GetStreetsNamesResponse")]
        WpfRentingApartementRacheli.ServiceReference1.DTOStreetsNames[] GetStreetsNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStreetsNames", ReplyAction="http://tempuri.org/IService1/GetStreetsNamesResponse")]
        System.Threading.Tasks.Task<WpfRentingApartementRacheli.ServiceReference1.DTOStreetsNames[]> GetStreetsNamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddStreetsNames", ReplyAction="http://tempuri.org/IService1/AddStreetsNamesResponse")]
        bool AddStreetsNames(WpfRentingApartementRacheli.ServiceReference1.DTOStreetsNames streetsNames);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddStreetsNames", ReplyAction="http://tempuri.org/IService1/AddStreetsNamesResponse")]
        System.Threading.Tasks.Task<bool> AddStreetsNamesAsync(WpfRentingApartementRacheli.ServiceReference1.DTOStreetsNames streetsNames);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateArae", ReplyAction="http://tempuri.org/IService1/UpdateAraeResponse")]
        bool UpdateArae(WpfRentingApartementRacheli.ServiceReference1.DTOAreas areas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateArae", ReplyAction="http://tempuri.org/IService1/UpdateAraeResponse")]
        System.Threading.Tasks.Task<bool> UpdateAraeAsync(WpfRentingApartementRacheli.ServiceReference1.DTOAreas areas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateApartments", ReplyAction="http://tempuri.org/IService1/UpdateApartmentsResponse")]
        bool UpdateApartments(WpfRentingApartementRacheli.ServiceReference1.DTOApartments apartment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateApartments", ReplyAction="http://tempuri.org/IService1/UpdateApartmentsResponse")]
        System.Threading.Tasks.Task<bool> UpdateApartmentsAsync(WpfRentingApartementRacheli.ServiceReference1.DTOApartments apartment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateraesCitiesStreet", ReplyAction="http://tempuri.org/IService1/UpdateraesCitiesStreetResponse")]
        bool UpdateraesCitiesStreet(WpfRentingApartementRacheli.ServiceReference1.DTOAraesCitiesStreet raesCitiesStreet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateraesCitiesStreet", ReplyAction="http://tempuri.org/IService1/UpdateraesCitiesStreetResponse")]
        System.Threading.Tasks.Task<bool> UpdateraesCitiesStreetAsync(WpfRentingApartementRacheli.ServiceReference1.DTOAraesCitiesStreet raesCitiesStreet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCities", ReplyAction="http://tempuri.org/IService1/UpdateCitiesResponse")]
        bool UpdateCities(WpfRentingApartementRacheli.ServiceReference1.DTOCities city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCities", ReplyAction="http://tempuri.org/IService1/UpdateCitiesResponse")]
        System.Threading.Tasks.Task<bool> UpdateCitiesAsync(WpfRentingApartementRacheli.ServiceReference1.DTOCities city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updatextras", ReplyAction="http://tempuri.org/IService1/UpdatextrasResponse")]
        bool Updatextras(WpfRentingApartementRacheli.ServiceReference1.DTOExtras extra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Updatextras", ReplyAction="http://tempuri.org/IService1/UpdatextrasResponse")]
        System.Threading.Tasks.Task<bool> UpdatextrasAsync(WpfRentingApartementRacheli.ServiceReference1.DTOExtras extra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateExtrasApartements", ReplyAction="http://tempuri.org/IService1/UpdateExtrasApartementsResponse")]
        bool UpdateExtrasApartements(WpfRentingApartementRacheli.ServiceReference1.DTOExtrasApartements ExtrasApartements);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateExtrasApartements", ReplyAction="http://tempuri.org/IService1/UpdateExtrasApartementsResponse")]
        System.Threading.Tasks.Task<bool> UpdateExtrasApartementsAsync(WpfRentingApartementRacheli.ServiceReference1.DTOExtrasApartements ExtrasApartements);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateHirers", ReplyAction="http://tempuri.org/IService1/UpdateHirersResponse")]
        bool UpdateHirers(WpfRentingApartementRacheli.ServiceReference1.DTOHirers hirer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateHirers", ReplyAction="http://tempuri.org/IService1/UpdateHirersResponse")]
        System.Threading.Tasks.Task<bool> UpdateHirersAsync(WpfRentingApartementRacheli.ServiceReference1.DTOHirers hirer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateImages", ReplyAction="http://tempuri.org/IService1/UpdateImagesResponse")]
        bool UpdateImages(WpfRentingApartementRacheli.ServiceReference1.DTOImages image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateImages", ReplyAction="http://tempuri.org/IService1/UpdateImagesResponse")]
        System.Threading.Tasks.Task<bool> UpdateImagesAsync(WpfRentingApartementRacheli.ServiceReference1.DTOImages image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateRentings", ReplyAction="http://tempuri.org/IService1/UpdateRentingsResponse")]
        bool UpdateRentings(WpfRentingApartementRacheli.ServiceReference1.DTORentings rentings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateRentings", ReplyAction="http://tempuri.org/IService1/UpdateRentingsResponse")]
        System.Threading.Tasks.Task<bool> UpdateRentingsAsync(WpfRentingApartementRacheli.ServiceReference1.DTORentings rentings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateStreetsNames", ReplyAction="http://tempuri.org/IService1/UpdateStreetsNamesResponse")]
        bool UpdateStreetsNames(WpfRentingApartementRacheli.ServiceReference1.DTOStreetsNames streetsName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateStreetsNames", ReplyAction="http://tempuri.org/IService1/UpdateStreetsNamesResponse")]
        System.Threading.Tasks.Task<bool> UpdateStreetsNamesAsync(WpfRentingApartementRacheli.ServiceReference1.DTOStreetsNames streetsName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteApartment", ReplyAction="http://tempuri.org/IService1/DeleteApartmentResponse")]
        bool DeleteApartment(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteApartment", ReplyAction="http://tempuri.org/IService1/DeleteApartmentResponse")]
        System.Threading.Tasks.Task<bool> DeleteApartmentAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteArea", ReplyAction="http://tempuri.org/IService1/DeleteAreaResponse")]
        bool DeleteArea(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteArea", ReplyAction="http://tempuri.org/IService1/DeleteAreaResponse")]
        System.Threading.Tasks.Task<bool> DeleteAreaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCity", ReplyAction="http://tempuri.org/IService1/DeleteCityResponse")]
        bool DeleteCity(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCity", ReplyAction="http://tempuri.org/IService1/DeleteCityResponse")]
        System.Threading.Tasks.Task<bool> DeleteCityAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteExtra", ReplyAction="http://tempuri.org/IService1/DeleteExtraResponse")]
        bool DeleteExtra(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteExtra", ReplyAction="http://tempuri.org/IService1/DeleteExtraResponse")]
        System.Threading.Tasks.Task<bool> DeleteExtraAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteStreetsName", ReplyAction="http://tempuri.org/IService1/DeleteStreetsNameResponse")]
        bool DeleteStreetsName(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteStreetsName", ReplyAction="http://tempuri.org/IService1/DeleteStreetsNameResponse")]
        System.Threading.Tasks.Task<bool> DeleteStreetsNameAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteHirer", ReplyAction="http://tempuri.org/IService1/DeleteHirerResponse")]
        bool DeleteHirer(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteHirer", ReplyAction="http://tempuri.org/IService1/DeleteHirerResponse")]
        System.Threading.Tasks.Task<bool> DeleteHirerAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteRenting", ReplyAction="http://tempuri.org/IService1/DeleteRentingResponse")]
        bool DeleteRenting(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteRenting", ReplyAction="http://tempuri.org/IService1/DeleteRentingResponse")]
        System.Threading.Tasks.Task<bool> DeleteRentingAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteAraesCitiesStreet", ReplyAction="http://tempuri.org/IService1/DeleteAraesCitiesStreetResponse")]
        bool DeleteAraesCitiesStreet(int idStreet, int idCities, int idArea);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteAraesCitiesStreet", ReplyAction="http://tempuri.org/IService1/DeleteAraesCitiesStreetResponse")]
        System.Threading.Tasks.Task<bool> DeleteAraesCitiesStreetAsync(int idStreet, int idCities, int idArea);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteExtrasApartement", ReplyAction="http://tempuri.org/IService1/DeleteExtrasApartementResponse")]
        bool DeleteExtrasApartement(int idExtra, int idApartment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteExtrasApartement", ReplyAction="http://tempuri.org/IService1/DeleteExtrasApartementResponse")]
        System.Threading.Tasks.Task<bool> DeleteExtrasApartementAsync(int idExtra, int idApartment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteImage", ReplyAction="http://tempuri.org/IService1/DeleteImageResponse")]
        bool DeleteImage(int idApartment, int numImage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteImage", ReplyAction="http://tempuri.org/IService1/DeleteImageResponse")]
        System.Threading.Tasks.Task<bool> DeleteImageAsync(int idApartment, int numImage);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WpfRentingApartementRacheli.ServiceReference1.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WpfRentingApartementRacheli.ServiceReference1.IService1>, WpfRentingApartementRacheli.ServiceReference1.IService1
    {
        
        public Service1Client()
        {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public WpfRentingApartementRacheli.ServiceReference1.DTOApartments[] GetApartments()
        {
            return base.Channel.GetApartments();
        }
        
        public System.Threading.Tasks.Task<WpfRentingApartementRacheli.ServiceReference1.DTOApartments[]> GetApartmentsAsync()
        {
            return base.Channel.GetApartmentsAsync();
        }
        
        public bool AddApartments(WpfRentingApartementRacheli.ServiceReference1.DTOApartments apartments)
        {
            return base.Channel.AddApartments(apartments);
        }
        
        public System.Threading.Tasks.Task<bool> AddApartmentsAsync(WpfRentingApartementRacheli.ServiceReference1.DTOApartments apartments)
        {
            return base.Channel.AddApartmentsAsync(apartments);
        }
        
        public WpfRentingApartementRacheli.ServiceReference1.DTOAreas[] GetAreas()
        {
            return base.Channel.GetAreas();
        }
        
        public System.Threading.Tasks.Task<WpfRentingApartementRacheli.ServiceReference1.DTOAreas[]> GetAreasAsync()
        {
            return base.Channel.GetAreasAsync();
        }
        
        public bool AddArea(WpfRentingApartementRacheli.ServiceReference1.DTOAreas areas)
        {
            return base.Channel.AddArea(areas);
        }
        
        public System.Threading.Tasks.Task<bool> AddAreaAsync(WpfRentingApartementRacheli.ServiceReference1.DTOAreas areas)
        {
            return base.Channel.AddAreaAsync(areas);
        }
        
        public WpfRentingApartementRacheli.ServiceReference1.DTOAraesCitiesStreet[] GetTOAraesCitiesStreets()
        {
            return base.Channel.GetTOAraesCitiesStreets();
        }
        
        public System.Threading.Tasks.Task<WpfRentingApartementRacheli.ServiceReference1.DTOAraesCitiesStreet[]> GetTOAraesCitiesStreetsAsync()
        {
            return base.Channel.GetTOAraesCitiesStreetsAsync();
        }
        
        public bool AddAraesCitiesStreet(WpfRentingApartementRacheli.ServiceReference1.DTOAraesCitiesStreet araesCitiesStreet)
        {
            return base.Channel.AddAraesCitiesStreet(araesCitiesStreet);
        }
        
        public System.Threading.Tasks.Task<bool> AddAraesCitiesStreetAsync(WpfRentingApartementRacheli.ServiceReference1.DTOAraesCitiesStreet araesCitiesStreet)
        {
            return base.Channel.AddAraesCitiesStreetAsync(araesCitiesStreet);
        }
        
        public WpfRentingApartementRacheli.ServiceReference1.DTOCities[] GetTOCities()
        {
            return base.Channel.GetTOCities();
        }
        
        public System.Threading.Tasks.Task<WpfRentingApartementRacheli.ServiceReference1.DTOCities[]> GetTOCitiesAsync()
        {
            return base.Channel.GetTOCitiesAsync();
        }
        
        public bool AddCities(WpfRentingApartementRacheli.ServiceReference1.DTOCities cities)
        {
            return base.Channel.AddCities(cities);
        }
        
        public System.Threading.Tasks.Task<bool> AddCitiesAsync(WpfRentingApartementRacheli.ServiceReference1.DTOCities cities)
        {
            return base.Channel.AddCitiesAsync(cities);
        }
        
        public WpfRentingApartementRacheli.ServiceReference1.DTOExtras[] GetExtras()
        {
            return base.Channel.GetExtras();
        }
        
        public System.Threading.Tasks.Task<WpfRentingApartementRacheli.ServiceReference1.DTOExtras[]> GetExtrasAsync()
        {
            return base.Channel.GetExtrasAsync();
        }
        
        public bool AddExtras(WpfRentingApartementRacheli.ServiceReference1.DTOExtras extras)
        {
            return base.Channel.AddExtras(extras);
        }
        
        public System.Threading.Tasks.Task<bool> AddExtrasAsync(WpfRentingApartementRacheli.ServiceReference1.DTOExtras extras)
        {
            return base.Channel.AddExtrasAsync(extras);
        }
        
        public WpfRentingApartementRacheli.ServiceReference1.DTOExtrasApartements[] GetTOExtrasApartements()
        {
            return base.Channel.GetTOExtrasApartements();
        }
        
        public System.Threading.Tasks.Task<WpfRentingApartementRacheli.ServiceReference1.DTOExtrasApartements[]> GetTOExtrasApartementsAsync()
        {
            return base.Channel.GetTOExtrasApartementsAsync();
        }
        
        public bool AddExtrasApartements(WpfRentingApartementRacheli.ServiceReference1.DTOExtrasApartements extrasApartements)
        {
            return base.Channel.AddExtrasApartements(extrasApartements);
        }
        
        public System.Threading.Tasks.Task<bool> AddExtrasApartementsAsync(WpfRentingApartementRacheli.ServiceReference1.DTOExtrasApartements extrasApartements)
        {
            return base.Channel.AddExtrasApartementsAsync(extrasApartements);
        }
        
        public WpfRentingApartementRacheli.ServiceReference1.DTOHirers[] GetTOHirers()
        {
            return base.Channel.GetTOHirers();
        }
        
        public System.Threading.Tasks.Task<WpfRentingApartementRacheli.ServiceReference1.DTOHirers[]> GetTOHirersAsync()
        {
            return base.Channel.GetTOHirersAsync();
        }
        
        public bool AddHirers(WpfRentingApartementRacheli.ServiceReference1.DTOHirers hirers)
        {
            return base.Channel.AddHirers(hirers);
        }
        
        public System.Threading.Tasks.Task<bool> AddHirersAsync(WpfRentingApartementRacheli.ServiceReference1.DTOHirers hirers)
        {
            return base.Channel.AddHirersAsync(hirers);
        }
        
        public WpfRentingApartementRacheli.ServiceReference1.DTOImages[] GetImages()
        {
            return base.Channel.GetImages();
        }
        
        public System.Threading.Tasks.Task<WpfRentingApartementRacheli.ServiceReference1.DTOImages[]> GetImagesAsync()
        {
            return base.Channel.GetImagesAsync();
        }
        
        public bool AddImages(WpfRentingApartementRacheli.ServiceReference1.DTOImages images)
        {
            return base.Channel.AddImages(images);
        }
        
        public System.Threading.Tasks.Task<bool> AddImagesAsync(WpfRentingApartementRacheli.ServiceReference1.DTOImages images)
        {
            return base.Channel.AddImagesAsync(images);
        }
        
        public WpfRentingApartementRacheli.ServiceReference1.DTORentings[] GetTORentings()
        {
            return base.Channel.GetTORentings();
        }
        
        public System.Threading.Tasks.Task<WpfRentingApartementRacheli.ServiceReference1.DTORentings[]> GetTORentingsAsync()
        {
            return base.Channel.GetTORentingsAsync();
        }
        
        public bool Addentings(WpfRentingApartementRacheli.ServiceReference1.DTORentings rentings)
        {
            return base.Channel.Addentings(rentings);
        }
        
        public System.Threading.Tasks.Task<bool> AddentingsAsync(WpfRentingApartementRacheli.ServiceReference1.DTORentings rentings)
        {
            return base.Channel.AddentingsAsync(rentings);
        }
        
        public WpfRentingApartementRacheli.ServiceReference1.DTOStreetsNames[] GetStreetsNames()
        {
            return base.Channel.GetStreetsNames();
        }
        
        public System.Threading.Tasks.Task<WpfRentingApartementRacheli.ServiceReference1.DTOStreetsNames[]> GetStreetsNamesAsync()
        {
            return base.Channel.GetStreetsNamesAsync();
        }
        
        public bool AddStreetsNames(WpfRentingApartementRacheli.ServiceReference1.DTOStreetsNames streetsNames)
        {
            return base.Channel.AddStreetsNames(streetsNames);
        }
        
        public System.Threading.Tasks.Task<bool> AddStreetsNamesAsync(WpfRentingApartementRacheli.ServiceReference1.DTOStreetsNames streetsNames)
        {
            return base.Channel.AddStreetsNamesAsync(streetsNames);
        }
        
        public bool UpdateArae(WpfRentingApartementRacheli.ServiceReference1.DTOAreas areas)
        {
            return base.Channel.UpdateArae(areas);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAraeAsync(WpfRentingApartementRacheli.ServiceReference1.DTOAreas areas)
        {
            return base.Channel.UpdateAraeAsync(areas);
        }
        
        public bool UpdateApartments(WpfRentingApartementRacheli.ServiceReference1.DTOApartments apartment)
        {
            return base.Channel.UpdateApartments(apartment);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateApartmentsAsync(WpfRentingApartementRacheli.ServiceReference1.DTOApartments apartment)
        {
            return base.Channel.UpdateApartmentsAsync(apartment);
        }
        
        public bool UpdateraesCitiesStreet(WpfRentingApartementRacheli.ServiceReference1.DTOAraesCitiesStreet raesCitiesStreet)
        {
            return base.Channel.UpdateraesCitiesStreet(raesCitiesStreet);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateraesCitiesStreetAsync(WpfRentingApartementRacheli.ServiceReference1.DTOAraesCitiesStreet raesCitiesStreet)
        {
            return base.Channel.UpdateraesCitiesStreetAsync(raesCitiesStreet);
        }
        
        public bool UpdateCities(WpfRentingApartementRacheli.ServiceReference1.DTOCities city)
        {
            return base.Channel.UpdateCities(city);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateCitiesAsync(WpfRentingApartementRacheli.ServiceReference1.DTOCities city)
        {
            return base.Channel.UpdateCitiesAsync(city);
        }
        
        public bool Updatextras(WpfRentingApartementRacheli.ServiceReference1.DTOExtras extra)
        {
            return base.Channel.Updatextras(extra);
        }
        
        public System.Threading.Tasks.Task<bool> UpdatextrasAsync(WpfRentingApartementRacheli.ServiceReference1.DTOExtras extra)
        {
            return base.Channel.UpdatextrasAsync(extra);
        }
        
        public bool UpdateExtrasApartements(WpfRentingApartementRacheli.ServiceReference1.DTOExtrasApartements ExtrasApartements)
        {
            return base.Channel.UpdateExtrasApartements(ExtrasApartements);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateExtrasApartementsAsync(WpfRentingApartementRacheli.ServiceReference1.DTOExtrasApartements ExtrasApartements)
        {
            return base.Channel.UpdateExtrasApartementsAsync(ExtrasApartements);
        }
        
        public bool UpdateHirers(WpfRentingApartementRacheli.ServiceReference1.DTOHirers hirer)
        {
            return base.Channel.UpdateHirers(hirer);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateHirersAsync(WpfRentingApartementRacheli.ServiceReference1.DTOHirers hirer)
        {
            return base.Channel.UpdateHirersAsync(hirer);
        }
        
        public bool UpdateImages(WpfRentingApartementRacheli.ServiceReference1.DTOImages image)
        {
            return base.Channel.UpdateImages(image);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateImagesAsync(WpfRentingApartementRacheli.ServiceReference1.DTOImages image)
        {
            return base.Channel.UpdateImagesAsync(image);
        }
        
        public bool UpdateRentings(WpfRentingApartementRacheli.ServiceReference1.DTORentings rentings)
        {
            return base.Channel.UpdateRentings(rentings);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateRentingsAsync(WpfRentingApartementRacheli.ServiceReference1.DTORentings rentings)
        {
            return base.Channel.UpdateRentingsAsync(rentings);
        }
        
        public bool UpdateStreetsNames(WpfRentingApartementRacheli.ServiceReference1.DTOStreetsNames streetsName)
        {
            return base.Channel.UpdateStreetsNames(streetsName);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateStreetsNamesAsync(WpfRentingApartementRacheli.ServiceReference1.DTOStreetsNames streetsName)
        {
            return base.Channel.UpdateStreetsNamesAsync(streetsName);
        }
        
        public bool DeleteApartment(int id)
        {
            return base.Channel.DeleteApartment(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteApartmentAsync(int id)
        {
            return base.Channel.DeleteApartmentAsync(id);
        }
        
        public bool DeleteArea(int id)
        {
            return base.Channel.DeleteArea(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAreaAsync(int id)
        {
            return base.Channel.DeleteAreaAsync(id);
        }
        
        public bool DeleteCity(int id)
        {
            return base.Channel.DeleteCity(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteCityAsync(int id)
        {
            return base.Channel.DeleteCityAsync(id);
        }
        
        public bool DeleteExtra(int id)
        {
            return base.Channel.DeleteExtra(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteExtraAsync(int id)
        {
            return base.Channel.DeleteExtraAsync(id);
        }
        
        public bool DeleteStreetsName(int id)
        {
            return base.Channel.DeleteStreetsName(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteStreetsNameAsync(int id)
        {
            return base.Channel.DeleteStreetsNameAsync(id);
        }
        
        public bool DeleteHirer(string id)
        {
            return base.Channel.DeleteHirer(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteHirerAsync(string id)
        {
            return base.Channel.DeleteHirerAsync(id);
        }
        
        public bool DeleteRenting(int id)
        {
            return base.Channel.DeleteRenting(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteRentingAsync(int id)
        {
            return base.Channel.DeleteRentingAsync(id);
        }
        
        public bool DeleteAraesCitiesStreet(int idStreet, int idCities, int idArea)
        {
            return base.Channel.DeleteAraesCitiesStreet(idStreet, idCities, idArea);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAraesCitiesStreetAsync(int idStreet, int idCities, int idArea)
        {
            return base.Channel.DeleteAraesCitiesStreetAsync(idStreet, idCities, idArea);
        }
        
        public bool DeleteExtrasApartement(int idExtra, int idApartment)
        {
            return base.Channel.DeleteExtrasApartement(idExtra, idApartment);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteExtrasApartementAsync(int idExtra, int idApartment)
        {
            return base.Channel.DeleteExtrasApartementAsync(idExtra, idApartment);
        }
        
        public bool DeleteImage(int idApartment, int numImage)
        {
            return base.Channel.DeleteImage(idApartment, numImage);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteImageAsync(int idApartment, int numImage)
        {
            return base.Channel.DeleteImageAsync(idApartment, numImage);
        }
    }
}
