//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apartment()
        {
            this.ExtrasApartements = new HashSet<ExtrasApartement>();
            this.Images = new HashSet<Image>();
            this.Rentings = new HashSet<Renting>();
        }
    
        public int IdApartment { get; set; }
        public string NameOwner { get; set; }
        public int IdStreet { get; set; }
        public string NumberHouse { get; set; }
        public int Floor { get; set; }
        public int NumberRooms { get; set; }
        public int NumberBeds { get; set; }
        public int MinimumPrice { get; set; }
        public int ExtraForBed { get; set; }
        public bool Status { get; set; }
        public string note { get; set; }
        public int IdCities { get; set; }
        public string PhoneOwner { get; set; }
    
        public virtual City City { get; set; }
        public virtual StreetsName StreetsName { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExtrasApartement> ExtrasApartements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Renting> Rentings { get; set; }
    }
}
