//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtrasApartement
    {
        public int IdExtra { get; set; }
        public int IdAapartment { get; set; }
        public bool Status { get; set; }
    
        public virtual Apartment Apartment { get; set; }
        public virtual Extra Extra { get; set; }
    }
}
