//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RacheliEntities : DbContext
    {
        public RacheliEntities()
            : base("name=RentingAppartmentRacheliEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apartment> Apartments { get; set; }
        public virtual DbSet<AraesCitiesStreet> AraesCitiesStreets { get; set; }
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Extra> Extras { get; set; }
        public virtual DbSet<ExtrasApartement> ExtrasApartements { get; set; }
        public virtual DbSet<Hirer> Hirers { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Renting> Rentings { get; set; }
        public virtual DbSet<StreetsName> StreetsNames { get; set; }
    }
}
