//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Renting
    {
        public int IdRenting { get; set; }
        public string IdHirer { get; set; }
        public int KodHapartment { get; set; }
        public System.DateTime Date { get; set; }
        public int SumPayment { get; set; }
        public int SumBeds { get; set; }
    
        public virtual Apartment Apartment { get; set; }
        public virtual Hirer Hirer { get; set; }
    }
}
